name: CI tests
on:
   push: null
   pull_request: null

jobs:
   build:
      runs-on: ubuntu-latest
      env:
         workdir: lego-collector

      name: Build with Java 11
      steps:
      -  uses: actions/checkout@v2
      
      -  name: Set up JDK 11
         uses: actions/setup-java@v1
         with:
            java-version: 11
         
      -  name: Cache Maven packages
         uses: actions/cache@v2
         with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
            restore-keys: ${{ runner.os }}-m2-
            
      -  name: Build with Maven
         run: >
            mvn verify 
            -Pjacoco coveralls:report 
            -DrepoToken=$COVERALLS_TOKEN 
            -DpullRequest=$PULL_REQUEST
         working-directory: ${{ env.workdir }}
         env:
            COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
            PULL_REQUEST: ${{ github.event.pull_request.number }}
         
      -  name: Generate Report
         run: mvn surefire-report:report-only site:site -DgenerateReports=false
         working-directory: ${{ env.workdir }}
         if: ${{ always() }}
         
      -  name: Upload JUnit Report
         uses: actions/upload-artifact@v2
         if: ${{ always() }}
         with:
            name: surefire-report-jdk-${{ matrix.java }}
            path: '**/target/site'