# This workflow will build a Java project with Maven
name: Java CI with Maven in Linux
on:
   push: null
   pull_request: null

   jobs:
      build:
         runs-on: ubuntu-latest

         steps:
         -  uses: actions/checkout@v2
         -  name: Set up JDK 8
            uses: actions/setup-java@v1
            with:
               java-version: 1.8
         -  name: Build with Maven
            run: mvn -f com.examples.myproject/pom.xml clean verify