name: CI tests
on:
   push: null
   pull_request: null

jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            include:
               - java: 8
                 additional-maven-args: "-Pjacoco"
               - java: 11
      env:
         workdir: lego-collector

      name: Build with Java ${{ matrix.java }}
      steps:
      -  uses: actions/checkout@v2
      
      -  name: Set up JDK ${{ matrix.java }}
         uses: actions/setup-java@v1
         with:
            java-version: ${{ matrix.java }}
         
      -  name: Cache Maven packages
         uses: actions/cache@v2
         with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
            restore-keys: ${{ runner.os }}-m2-
            
      -  name: Build with Maven
         run: mvn verify ${{ matrix.additional-maven-args }}
         working-directory: ${{ env.workdir }}
         
      -  name: Generate Report
         run: mvn surefire-report:report-only site:site -DgenerateReports=false
         working-directory: ${{ env.workdir }}
         if: ${{ always() }}
         
      -  name: Upload JUnit Report
         uses: actions/upload-artifact@v2
         if: ${{ always() }}
         with:
            name: surefire-report-jdk-${{ matrix.java }}
            path: '**/target/site'